package com.yumi.chatbot.domain;

public enum Intent {
  GREETING,
  PRODUCT_AVAILABILITY,
  PURCHASE_INTENT,
  QUESTION,
  FAQ,
  DELIVERY_TIME,
  ORDER_STATUS,
  RECOMMENDATION,
  ADD_TO_CART,
  ADD_TO_CART_AWAIT_CONFIRM,
  NO_AUTHORIZED,
  PRODUCT_LIST,
  UNKNOWN
}