-- Secciones
INSERT INTO about_sections (key, title, subtitle) VALUES
('about', 'Nuestra Historia', 'Conoce más sobre Yumi, tu tienda de confianza'),
('faq', 'Preguntas Frecuentes', NULL),
('policies', 'Políticas', NULL);

-- Tarjetas
INSERT INTO about_cards (section_key, icon, title, description) VALUES
('about', 'ShoppingBag', 'Variedad de Productos', 'Miles de productos de las mejores marcas a tu alcance'),
('about', 'Truck', 'Envíos Rápidos', 'Entrega en 24-48 horas en todo el territorio nacional'),
('about', 'Shield', 'Compra Segura', 'Protección en todas tus transacciones y datos encriptados'),
('about', 'Heart', 'Atención al Cliente', 'Soporte dedicado 24/7 para resolver todas tus dudas');

-- FAQs
INSERT INTO about_faqs (question, answer) VALUES
('¿Cómo puedo hacer un pedido?', 'Hacer un pedido es muy sencillo. Navega por nuestro catálogo, agrega los productos que desees al carrito, completa el proceso de pago y listo. Recibirás una confirmación por email con todos los detalles de tu pedido.'),
('¿Cuáles son los métodos de pago aceptados?', 'Aceptamos tarjetas de crédito y débito (Visa, Mastercard, American Express), transferencias bancarias y pagos contra entrega en algunas zonas. Todos los pagos son procesados de forma segura mediante encriptación SSL.'),
('¿Cuánto tarda la entrega?', 'Los tiempos de entrega varían según tu ubicación. En la mayoría de ciudades principales, la entrega se realiza en 24-48 horas. Para zonas remotas, puede tomar de 3 a 5 días hábiles. Recibirás un número de seguimiento para rastrear tu pedido en tiempo real.'),
('¿Puedo devolver o cambiar un producto?', 'Sí, aceptamos devoluciones y cambios dentro de los 30 días posteriores a la recepción del producto. El artículo debe estar en su empaque original, sin uso y con todas sus etiquetas. Los gastos de envío de devolución corren por cuenta del cliente, excepto en casos de productos defectuosos.'),
('¿Los precios incluyen IVA?', 'Sí, todos nuestros precios mostrados incluyen IVA. Lo que ves es lo que pagas, sin cargos ocultos adicionales. En el resumen de compra podrás ver el desglose completo de tu pedido.'),
('¿Ofrecen garantía en los productos?', 'Todos nuestros productos cuentan con garantía del fabricante. El tiempo de garantía varía según el producto y marca (generalmente de 6 meses a 2 años). Adicionalmente, ofrecemos una garantía de satisfacción de 30 días en todos nuestros productos.'),
('¿Hacen envíos internacionales?', 'Actualmente realizamos envíos únicamente a nivel nacional. Sin embargo, estamos trabajando para expandir nuestros servicios de envío internacional muy pronto. Suscríbete a nuestro newsletter para ser el primero en enterarte cuando estemos disponibles en tu país.'),
('¿Cómo puedo contactar con atención al cliente?', 'Puedes contactarnos a través de nuestro chat en línea (disponible en la esquina inferior derecha), por email a soporte@yumi.com, o por teléfono al 1-800-YUMI de lunes a domingo de 8:00 AM a 10:00 PM. Nuestro equipo está siempre listo para ayudarte.');

-- Políticas
INSERT INTO about_policies (title, content) VALUES
('Política de Privacidad', 'Recopilación de Información\nEn Yumi recopilamos información personal que nos proporcionas al crear una cuenta, realizar un pedido o contactarnos. Esto incluye nombre, dirección de correo electrónico, dirección de envío, información de pago y número de teléfono.\n\nUso de la Información\nUtilizamos tu información para procesar pedidos, mejorar nuestros servicios, comunicarnos contigo sobre tu cuenta o pedidos, y enviarte ofertas promocionales (solo si has dado tu consentimiento). Nunca vendemos tu información personal a terceros.\n\nSeguridad de los Datos\nImplementamos medidas de seguridad técnicas y organizativas para proteger tus datos personales contra acceso no autorizado, pérdida o alteración. Toda la información sensible se transmite mediante tecnología SSL encriptada.\n\nCookies\nUtilizamos cookies para mejorar tu experiencia de navegación, recordar tus preferencias y analizar el tráfico del sitio. Puedes configurar tu navegador para rechazar cookies, aunque esto puede afectar algunas funcionalidades del sitio.'),
('Términos y Condiciones', 'Uso del Sitio Web\nAl acceder y utilizar nuestro sitio web, aceptas cumplir con estos términos y condiciones. Debes ser mayor de 18 años o tener el consentimiento de un padre o tutor para realizar compras.\n\nPrecios y Disponibilidad\nTodos los precios están sujetos a cambios sin previo aviso. Nos esforzamos por mantener información precisa sobre la disponibilidad de productos, pero no podemos garantizar que todos los artículos mostrados estén en stock.\n\nProceso de Compra\nAl realizar un pedido, estás haciendo una oferta de compra. Nos reservamos el derecho de rechazar cualquier pedido por cualquier motivo. Una vez confirmado el pedido, recibirás un email de confirmación con los detalles de tu compra.\n\nDevoluciones y Reembolsos\nAceptamos devoluciones dentro de los 30 días posteriores a la recepción. Los productos deben estar en su estado original. Los reembolsos se procesarán en un plazo de 5-10 días hábiles después de recibir el producto devuelto.\n\nPropiedad Intelectual\nTodo el contenido del sitio web, incluyendo textos, gráficos, logos e imágenes, es propiedad de Yumi y está protegido por leyes de derechos de autor. No está permitida la reproducción sin autorización expresa.\n\nLimitación de Responsabilidad\nYumi no será responsable de daños indirectos, incidentales o consecuentes que resulten del uso de nuestros productos o servicios. Nuestra responsabilidad se limita al valor del producto comprado.\n\nModificaciones\nNos reservamos el derecho de modificar estos términos y condiciones en cualquier momento. Los cambios entrarán en vigor inmediatamente después de su publicación en el sitio web. Te recomendamos revisar periódicamente esta página.');